# ===============================
# Application
# ===============================
spring.application.name=sb_ibms

server.port=${PORT:8080}
server.address=0.0.0.0

spring.main.allow-circular-references=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ===============================
# PostgreSQL (Render)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# HikariCP
# ===============================
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# ===============================
# Session
# ===============================
spring.session.store-type=none

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ===============================
# bKash
# ===============================
bkash.base-url=https://tokenized.sandbox.bka.sh/v2
bkash.username=01770618567
bkash.password=D7DaC<*E*eG
bkash.app-key=0vWQuCRGiUX7EPVjQDr0EUAYtc
bkash.app-secret=jcUNPBgbcqEDedNKdvE4G1cAK7D3hCjmJccNPZZBq96QIxxwAMEx

# Update later with production frontend URL
bkash.callback-url=https://your-frontend-domain.com/callback

# ===============================
# File Upload
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB